"""Create demo evidence directory for TRACE-AI-FR analysis."""
import os
import sqlite3

base = r"C:\UNCC\ITIS-5250-092(Comp-For)\Project\code\demo_evidence"

# Create directory structure mimicking a Windows user profile
dirs = [
    "Users/JohnDoe/AppData/Local/Google/Chrome/User Data/Default",
    "Users/JohnDoe/AppData/Local/Google/Chrome/User Data/Default/Local Storage/leveldb",
    "Users/JohnDoe/AppData/Roaming/Microsoft/Windows/Recent",
    "Users/JohnDoe/Downloads",
    "Windows/Prefetch",
]
for d in dirs:
    os.makedirs(os.path.join(base, d), exist_ok=True)

# 1) Chrome History DB
hist_path = os.path.join(base, "Users/JohnDoe/AppData/Local/Google/Chrome/User Data/Default/History")
conn = sqlite3.connect(hist_path)
c = conn.cursor()
c.execute("CREATE TABLE urls (id INTEGER PRIMARY KEY, url TEXT, title TEXT, visit_count INTEGER, last_visit_time INTEGER)")
c.execute("CREATE TABLE visits (id INTEGER PRIMARY KEY, url INTEGER, visit_time INTEGER, from_visit INTEGER, transition INTEGER)")
ts_base = 13350000000000000  # Chrome epoch timestamp
entries = [
    ("https://chatgpt.com/", "ChatGPT", 5, ts_base),
    ("https://chatgpt.com/c/abc123", "ChatGPT - Crime scene analysis", 3, ts_base + 3600000000),
    ("https://chat.openai.com/chat", "ChatGPT", 2, ts_base + 7200000000),
    ("https://claude.ai/", "Claude", 4, ts_base + 1800000000),
    ("https://claude.ai/chat/def456", "Claude - Evidence review", 2, ts_base + 5400000000),
    ("https://gemini.google.com/app", "Gemini", 3, ts_base + 9000000000),
    ("https://gemini.google.com/app/xyz789", "Gemini - Forensic assistance", 1, ts_base + 10800000000),
]
for i, (url, title, vc, ts) in enumerate(entries, 1):
    c.execute("INSERT INTO urls VALUES (?,?,?,?,?)", (i, url, title, vc, ts))
    c.execute("INSERT INTO visits VALUES (?,?,?,0,0)", (i, i, ts))
conn.commit()
conn.close()

# 2) Chrome Cookies DB
cookie_path = os.path.join(base, "Users/JohnDoe/AppData/Local/Google/Chrome/User Data/Default/Cookies")
conn = sqlite3.connect(cookie_path)
c = conn.cursor()
c.execute("CREATE TABLE cookies (creation_utc INTEGER, host_key TEXT, name TEXT, value TEXT, path TEXT, expires_utc INTEGER, is_secure INTEGER, is_httponly INTEGER, last_access_utc INTEGER, encrypted_value BLOB)")
cookies = [
    (ts_base, ".chatgpt.com", "__cf_bm", "session_val", "/", ts_base + 86400000000, 1, 1, ts_base + 3600000000, b""),
    (ts_base, ".openai.com", "_cfuvid", "tracking_val", "/", ts_base + 86400000000, 1, 0, ts_base + 3600000000, b""),
    (ts_base + 1000000, ".claude.ai", "__cf_bm", "claude_sess", "/", ts_base + 86400000000, 1, 1, ts_base + 5400000000, b""),
    (ts_base + 2000000, ".gemini.google.com", "NID", "gemini_val", "/", ts_base + 86400000000, 1, 0, ts_base + 9000000000, b""),
]
for cookie in cookies:
    c.execute("INSERT INTO cookies VALUES (?,?,?,?,?,?,?,?,?,?)", cookie)
conn.commit()
conn.close()

# 3) AI-related downloads
dl_dir = os.path.join(base, "Users/JohnDoe/Downloads")
files = {
    "ChatGPT_Crime_Scene_Analysis.pdf": "AI-generated crime scene analysis from ChatGPT GPT-4o",
    "claude_response_export.txt": "Claude AI response export - evidence review notes",
    "gemini_forensic_notes.md": "# Gemini Forensic Notes\nGenerated by Gemini Pro",
}
for fname, content in files.items():
    with open(os.path.join(dl_dir, fname), "w") as f:
        f.write(content)

# 4) Local Storage trace
ls_dir = os.path.join(base, "Users/JohnDoe/AppData/Local/Google/Chrome/User Data/Default/Local Storage/leveldb")
with open(os.path.join(ls_dir, "chatgpt_trace.log"), "w") as f:
    f.write("https://chatgpt.com model:gpt-4o conversation_id:abc123")

# 5) Prefetch file (simulated)
with open(os.path.join(base, "Windows/Prefetch/CHROME.EXE-ABC12345.pf"), "wb") as f:
    f.write(b"\x00" * 64 + b"chatgpt.com" + b"\x00" * 64)

print("Demo evidence created successfully at:", base)
