# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all

datas = [('ai_usage_evidence_analyzer', 'ai_usage_evidence_analyzer')]
binaries = []
hiddenimports = [
    'ai_usage_evidence_analyzer',
    'ai_usage_evidence_analyzer.__main__',
    'ai_usage_evidence_analyzer.acquisition_bridge',
    'ai_usage_evidence_analyzer.adjudication',
    'ai_usage_evidence_analyzer.capability_registry',
    'ai_usage_evidence_analyzer.carving',
    'ai_usage_evidence_analyzer.caveats',
    'ai_usage_evidence_analyzer.claim_ladder',
    'ai_usage_evidence_analyzer.cli',
    'ai_usage_evidence_analyzer.confidence',
    'ai_usage_evidence_analyzer.correlation',
    'ai_usage_evidence_analyzer.docx_parser',
    'ai_usage_evidence_analyzer.docx_report',
    'ai_usage_evidence_analyzer.e01_handler',
    'ai_usage_evidence_analyzer.engine',
    'ai_usage_evidence_analyzer.evidence_exhibit',
    'ai_usage_evidence_analyzer.forensic_checklist',
    'ai_usage_evidence_analyzer.fr_assessment',
    'ai_usage_evidence_analyzer.governance',
    'ai_usage_evidence_analyzer.llm_narrator',
    'ai_usage_evidence_analyzer.matrix',
    'ai_usage_evidence_analyzer.models',
    'ai_usage_evidence_analyzer.parser_registry',
    'ai_usage_evidence_analyzer.partition_analysis',
    'ai_usage_evidence_analyzer.persistence',
    'ai_usage_evidence_analyzer.raw_inspector',
    'ai_usage_evidence_analyzer.recovery',
    'ai_usage_evidence_analyzer.repo_reality_check',
    'ai_usage_evidence_analyzer.report_generator',
    'ai_usage_evidence_analyzer.signatures',
    'ai_usage_evidence_analyzer.storage',
    'ai_usage_evidence_analyzer.tool_registry',
    'ai_usage_evidence_analyzer.ui_checklist',
    'ai_usage_evidence_analyzer.validation',
    'ai_usage_evidence_analyzer.voice_evidence',
    'ai_usage_evidence_analyzer.parsers',
    'ai_usage_evidence_analyzer.parsers.ai_tool_scanner',
    'ai_usage_evidence_analyzer.parsers.antiforensics_parsers',
    'ai_usage_evidence_analyzer.parsers.browser_parsers',
    'ai_usage_evidence_analyzer.parsers.c2pa_parser',
    'ai_usage_evidence_analyzer.parsers.chatgpt_export_parser',
    'ai_usage_evidence_analyzer.parsers.content_parsers',
    'ai_usage_evidence_analyzer.parsers.generated_asset_parser',
    'ai_usage_evidence_analyzer.parsers.iphone_parsers',
    'ai_usage_evidence_analyzer.parsers.macos_parsers',
    'ai_usage_evidence_analyzer.parsers.memory_pcap_parser',
    'ai_usage_evidence_analyzer.parsers.plugin_parsers',
    'ai_usage_evidence_analyzer.parsers.provider_export_parser',
    'ai_usage_evidence_analyzer.parsers.recovery_parsers',
    'ai_usage_evidence_analyzer.parsers.shared_link_parser',
    'ai_usage_evidence_analyzer.parsers.windows_parsers',
    'docx',
    'lxml',
]
tmp_ret = collect_all('docx')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]


a = Analysis(
    ['desktop_app.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'torchaudio',
        'scipy', 'pandas', 'matplotlib', 'mpl_toolkits',
        'IPython', 'ipykernel', 'ipywidgets', 'jupyter',
        'notebook', 'nbformat', 'nbconvert', 'nbclient',
        'jedi', 'parso',
        'zmq', 'websockets',
        'jsonschema', 'jsonschema_specifications',
        'pygments', 'rich',
        'pytest', 'py', '_pytest',
        'setuptools', 'pkg_resources', 'pip',
        'numpy', 'PIL',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TRACE-AI-FR',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
